#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bomba.Resource", IsApplication=true)]

namespace Bomba
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030000
			public const int big_button = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int middle_button = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int small_button = 2130903042;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonActivation = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int buttonLock = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int buttonLockOk = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int buttonOk = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int buttonTest = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int editTextIp = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textViewBomba = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int UI = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int activation_success = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int bomb_ip = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int button_activate = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button_ok = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int button_try = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int default_ip = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int lock_ip = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int lock_ok = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
